
:trello:
  :public_key: #get these here https://trello.com/1/appKey/generate
  :secret_key: #get these here https://trello.com/1/appKey/generate
  :token:      #tokens: https://trello.com/docs/gettingstarted/index.html#token   #used for accessing private board data or getting specific permissions. needed on a per-board basis
  :boards:
    - '50296f64955afc811b116157' #trelly board
:rally:
  :username:   #rally username
  :password:   #rally password
  :workspace:  "Sandbox - practice here"